# Generated by Django 5.2.8 on 2025-11-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="available_for",
            field=models.CharField(
                choices=[
                    ("rent", "Rent"),
                    ("exchange", "Exchange"),
                    ("donate", "Donate"),
                ],
                max_length=50,
            ),
        ),
    ]
