# Generated by Django 5.2.8 on 2025-11-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookrequest",
            name="exchange_book",
            field=models.ForeignKey(
                blank=True,
                help_text="Required only for exchange requests",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_requests",
                to="core.book",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_users",
                to="core.book",
            ),
        ),
    ]
