# Generated by Django 5.2.8 on 2025-11-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_bookrequest_exchange_book_alter_wishlist_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("nonfiction", "Non-Fiction"),
                    ("fantasy", "Fantasy"),
                    ("mystery", "Mystery"),
                    ("romance", "Romance"),
                    ("thriller", "Thriller"),
                    ("science", "Science"),
                    ("history", "History"),
                    ("biography", "Biography"),
                    ("selfhelp", "Self Help"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
